# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        env:
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
          CONTAINER_USER: ${{ secrets.CONTAINER_USER }}
          HOST_PORT: ${{ secrets.HOST_PORT }}
      - run: docker build -t "$CONTAINER_NAME":"$CONTAINER_USER" .
      - run: chmod u+x container-killer.sh
      - run: ./container-killer.sh "$CONTAINER_NAME"
      - run: docker run -p "$HOST_PORT":3000 --restart=always --name "$CONTAINER_NAME" -d "$CONTAINER_NAME":"$CONTAINER_USER"
